// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { Linking } from "react-native";
import InAppBrowser from 'react-native-inappbrowser-reborn';
import InAppBrowser334 from 'react-native-inappbrowser-reborn334';
// END EXTRA CODE

/**
 * @param {string} url
 * @param {"OIDC.ENU_Target.InAppBrowser"|"OIDC.ENU_Target.SystemBrowser"} target
 * @returns {Promise.<void>}
 */
export async function JS_OpenAuthURL(url, target) {
	// BEGIN USER CODE
	if (target === "SystemBrowser") {
		await Linking.openURL(url);
	} else {
		const deepLink = mx.session.getConstants().find(item => item.name === "OIDC.MobileURLScheme").value;
		//Mx 8+9 compatibility: use react-native-inappbrowser@3.3.4 for mx8 and 3.6.3 for mx9
		const openAuth = mx.version[0] === '8' ? InAppBrowser334.openAuth : InAppBrowser.openAuth;
		
		openAuth(url, deepLink, {
			// iOS Properties
			ephemeralWebSession: false,
			// Android Properties
			showTitle: false,
			enableUrlBarHiding: true,
			enableDefaultShare: false
		}).then((response) => {
			if (
			response.type === 'success' && response.url) {
			Linking.openURL(response.url)
			}
		})}
	return;
	// END USER CODE
}
