// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import AsyncStorage from "@react-native-community/async-storage";
// END EXTRA CODE

/**
 * Given a value, store it as the mobile auth token to be used during app startup.
 * @param {string} value - This field is required.
 * @returns {Promise.<void>}
 */
export async function SetToken(value) {
	// BEGIN USER CODE
    if (!value) {
        return Promise.reject(new Error("Input parameter 'Value' is required"));
    }
    await mx.session.tokenStore.set(value);
	// END USER CODE
}
