// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdfparsertesting.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetLastTwoWords extends CustomJavaAction<java.lang.String>
{
	private java.lang.String InputString;

	public GetLastTwoWords(IContext context, java.lang.String InputString)
	{
		super(context);
		this.InputString = InputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String[] parts = InputString.split(" ");
		String lastWord = parts[parts.length - 1];
		String PenultimateWord = parts[parts.length - 2];
		String Last2Words= "";
		 Last2Words = PenultimateWord + " " + lastWord;
		return(Last2Words);
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetLastTwoWords";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
